version: '3.8'

services:

  app:
    build: "./.docker_images/going_live_reloader"
    image: "going_live_reloader:dev"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - type: "bind"
        source: ./
        target: "/home/node/app"
    ports:
      - "3001:3001"
    depends_on:
      - database

  database:
    image: 'postgres:15.1'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'going-live-db1:/var/lib/postgresql/data'
      - ./database/pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "goinglive", "-U", "goinglive"]
      retries: 3
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@goinglive.com
      PGADMIN_DEFAULT_PASSWORD: admin
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  going-live-db1:
    driver: local
  pgadmin-data:
    driver: local
