version: '3.8'

services:

  app:
    build: "./.docker_images/go_live_reloader"
    image: "go_live_reloader:dev"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - type: "bind"
        source: ./
        target: "/home/node/app"
    ports:
      - "3001:3000"
    depends_on:
      - database

  database:
    image: 'postgres:15.1'
    ports:
        - '5433:5432'
    environment:
        POSTGRES_DB: 'goinglive'
        POSTGRES_USER: 'goinglive'
        POSTGRES_PASSWORD: 'goinglive'
    volumes:
        - 'going-live-db1:/var/lib/postgresql/data'
    healthcheck:
        test: ["CMD", "pg_isready", "-q", "-d", "goinglive", "-U", "goinglive"]
        retries: 3
        timeout: 5s

volumes:
    going-live-db1:
      driver: local